server:
    port: 8084
zuul:
  routes:
    oauth:
      path: /oauth/**
      sensitiveHeaders:
      url: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect
  Servlet30WrapperFilter:
    pre:
      disable:true